version: 2.1

jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: Build and run the development environment container.
          command: make ready
      - run:
          name: Run the CI suite.
          command: make ci

  tooling-vscode-publish:
    executor: node
    steps:
      - checkout
      - restore_cache:
          keys:
            - >-
              v1-node-cache-{{ .Branch }}-{{ checksum "tooling/vscode/package-lock.json"
              }}
            - 'v1-node-cache-{{ .Branch }}'
            - v1-node-cache-
      - run:
          working_directory: tooling/vscode
          command: npm install
      - save_cache:
          key: 'v1-node-cache-{{ .Branch }}-{{ checksum "tooling/vscode/package-lock.json" }}'
          paths:
            - node_modules
      - run:
          name: Publish
          working_directory: tooling/vscode
          command: npx vsce publish -p $VSCODE_MARKETPLACE_TOKEN 2>&1 | tee /dev/stderr | grep -E 'DONE|Version number cannot be the same'

workflows:
  build: { jobs: [build] }
  tooling-vscode-publish: { jobs: [tooling-vscode-publish] }
